---
- name: Copy the Citrix Policy input file
  win_copy:
    src: CitrixPolicy.txt
    dest: '{{ directory_install }}\Citrix'

- name: Configure Site
  script: config.ps1
  args:
    creates: '{{ directory_logging }}done-config.txt'
  environment:
    citrix_siteconfig_vdahostname: "{{ citrix_siteconfig_vdahostname }}"
    citrix_siteconfig_machinecatalog: "{{ citrix_siteconfig_machinecatalog }}"
    citrix_siteconfig_deliverygroup: "{{ citrix_siteconfig_deliverygroup }}"
    citrix_siteconfig_desktop: "{{ citrix_siteconfig_desktop }}"
    citrix_siteconfig_usergroup: "{{ citrix_siteconfig_usergroup }}"