---
- name: Copy the Citrix Policy input file
  win_copy:
    src: CitrixPolicy.txt
    dest: '{{ win_directory_install }}'

- name: Configure Site
  script: config.ps1
  args:
    creates: '{{ win_directory_logging}}done-config.txt'
  environment:
    citrix_siteconfig_vdahostname: "{{ citrix_siteconfig_vdahostname }}"
    citrix_siteconfig_machinecatalog: "{{ citrix_siteconfig_machinecatalog }}"
    citrix_siteconfig_deliverygroup: "{{ citrix_siteconfig_deliverygroup }}"
    citrix_siteconfig_desktop: "{{ citrix_siteconfig_desktop }}"
    citrix_siteconfig_usergroup: "{{ citrix_siteconfig_usergroup }}"