---
- name: Create local Folder
  win_file:
    path: '{{ citrix_logfolder }}'
    state: directory

- name: Copy the Citrix Policy input file
  win_copy:
    src: CitrixPolicy.txt
    dest: '{{ citrix_installfolder }}'

- name: Copy the Citrix config script
  win_copy:
    src: CitrixPolicy.txt
    dest: '{{ citrix_installfolder }}'

- name: Configure Site
  script: config.ps1
  args:
    creates: '{{ citrix_logfolder }}\done-config.txt'
  environment:
    citrix_siteconfig_vdahostname: "{{ citrix_siteconfig_vdahostname }}"
    citrix_siteconfig_machinecatalog: "{{ citrix_siteconfig_machinecatalog }}"
    citrix_siteconfig_deliverygroup: "{{ citrix_siteconfig_deliverygroup }}"
    citrix_siteconfig_desktop: "{{ citrix_siteconfig_desktop }}"
    citrix_siteconfig_usergroup: "{{ citrix_siteconfig_usergroup }}"